backend:
  name: git-gateway
  branch: main

media_folder: "immagini"
public_folder: "/immagini"

locale: 'it'

collections:
  - name: "articoli"
    label: "Articoli"
    label_singular: "Articolo"
    folder: "_articoli"
    create: true
    slug: "{{slug}}"
    identifier_field: "titolo"
    fields:
      - { label: "Titolo", name: "titolo", widget: "string" }
      - { label: "Titolo corsivo", name: "titolo_em", widget: "string", required: false }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Luogo o tema", name: "luogo", widget: "string" }
      - { label: "Autore", name: "autore", widget: "string", default: "Francesco Amirante" }
      - { label: "Minuti di lettura", name: "minuti", widget: "number", value_type: "int", default: 5 }
      - { label: "Foto copertina", name: "copertina", widget: "image" }
      - { label: "Breve estratto", name: "estratto", widget: "string" }
      - { label: "Testo introduttivo", name: "intro", widget: "text" }
      - label: "Contenuto articolo"
        name: "contenuto"
        widget: "list"
        label_singular: "Blocco"
        types:
          - label: "Paragrafo di testo"
            name: "paragrafo"
            widget: "object"
            fields:
              - { label: "Testo", name: "testo", widget: "text" }
          - label: "Foto"
            name: "foto"
            widget: "object"
            fields:
              - { label: "Immagine", name: "immagine", widget: "image" }
              - { label: "Didascalia", name: "didascalia", widget: "string", required: false }
          - label: "Citazione"
            name: "citazione"
            widget: "object"
            fields:
              - { label: "Testo", name: "testo", widget: "string" }
              - { label: "Parte in oro", name: "em", widget: "string", required: false }
      - { label: "Pubblica", name: "pubblicato", widget: "boolean", default: true }
